### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by lxBa0** [VHellendoorn/Code-LMs#15]
您好
可以帮我看下报错吗
`No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
NeoXArgs.from_ymls() ['configs/text_generation.yml', 'checkpoints/configs/local_setup.yml', 'checkpoints/configs/2-7B.yml']
INFO:root:NeoXArgs.calculate_derived() Total number of GPUs determined to be: 0
Traceback (most recent call last):
  File "./deepy.py", line 29, in <module>
    neox_args = NeoXArgs.consume_deepy_args()
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 304, in consume_deepy_args
    neox_args = cls.from_ymls(paths_to_yml_files=conf_files, overwrite_values=overwrite_values)
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 199, in from_ymls
    return cls(**config)
  File "<string>", line 184, in __init__
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 106, in __post_init__
    self.calculate_derived()
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 656, in calculate_derived
    self.check_batch_parameters(
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 570, in check_batch_parameters
    assert (
AssertionError: Train batch size: 0 has to be greater than 0`
谢谢～

**Comment by urialon** [comment]
Hi @ipsaxiaobo ,
Thank you for your interest in our project!

Can you please explain (in English) what did you do, what did you run, what OS system do you have, whether there is a GPU or not, and any other detail that might be relevant?

**Comment by VHellendoorn** [comment]
Closing due to inactivity.
