### ISSUE TITLE
PlaidML support for (MacOS)

### ISSUE THREAD

**Issue by XoxRumbleLorexoX** [VHellendoorn/Code-LMs#24]
I am currently on a Mac Pro with a AMD Radeon Pro 580X but the code generation doesn't complete due to this error. 
```
NeoXArgs.from_ymls() ['configs/text_generation.yml', 'configs/local_setup.yml', 'configs/2-7B.yml']
INFO:root:NeoXArgs.calculate_derived() Total number of GPUs determined to be: 0
Traceback (most recent call last):
  File "/Users/xoxrumblelorexox/Desktop/Workbash/polyai/checkpoints/checkpoints/./gpt-neox-main/deepy.py", line 28, in <module>
    neox_args = NeoXArgs.consume_deepy_args()
  File "/Users/xoxrumblelorexox/Desktop/Workbash/polyai/checkpoints/checkpoints/gpt-neox-main/megatron/neox_arguments/arguments.py", line 321, in consume_deepy_args
    neox_args = cls.from_ymls(
  File "/Users/xoxrumblelorexox/Desktop/Workbash/polyai/checkpoints/checkpoints/gpt-neox-main/megatron/neox_arguments/arguments.py", line 201, in from_ymls
    return cls(**config)
  File "<string>", line 186, in __init__
  File "/Users/xoxrumblelorexox/Desktop/Workbash/polyai/checkpoints/checkpoints/gpt-neox-main/megatron/neox_arguments/arguments.py", line 106, in __post_init__
    self.calculate_derived()
  File "/Users/xoxrumblelorexox/Desktop/Workbash/polyai/checkpoints/checkpoints/gpt-neox-main/megatron/neox_arguments/arguments.py", line 675, in calculate_derived
    self.check_batch_parameters(
  File "/Users/xoxrumblelorexox/Desktop/Workbash/polyai/checkpoints/checkpoints/gpt-neox-main/megatron/neox_arguments/arguments.py", line 589, in check_batch_parameters
    assert (
AssertionError: Train batch size: 0 has to be greater than 0
```

After a while i realised that tensorflow doesn't recognise non-Nividia GPUs.
There should be a disclaimer about this on the page. The only way around i found was to use PlaidML, but i am still getting the same error (probably because PlaidML only supports Keras)

Sorry, if already known.

**Comment by XoxRumbleLorexoX** [comment]
```
raise ValueError('{}.__spec__ is None'.format(name))
ValueError: tensorflow.__spec__ is None
```

Trying to run this on MacOS - i have tensorflow=1.14.0 due to nGraph bridge requiring this version, also i am running PlaidML to be able to use the AMD GPU i have 8GB.

I keep throwing errors. What virtualisation is a perfect environment to run this on?

I am finding this unusable on MacOSX

**Comment by VHellendoorn** [comment]
Hi, I am sorry this hasn't been working for you. I do not believe the issue you are facing are due to MacOS.  At this time, few deep learning toolkits support AMD GPUs, since most rely on NVidia's CUDA. Running this code on an AMD GPU is thus untested and likely to be a major chore, as you have found as well.

In any case, this repository servers only to provide trained models; the underlying toolkit for the models that are currently available is [GPT-NeoX](https://github.com/EleutherAI/gpt-neox/), which is itself built in part on NVidia's MegatronLM. We do not maintain this tool. If you want to pursue running these models on an AMD accelerator, I would suggest pinging the creators of these underlying repositories, though as I mentioned above, in my experience there is typically little interest in supporting these GPUs.
